apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      traefik.ingress.kubernetes.io/app-root: /
    name: rabbitmq-management
    namespace: rabbitmq-ns
  spec:
    rules:
    - host: 4bplus001.lan
      http:
        paths:
        - backend:
            serviceName: ingress-75f007bf592e2594982949ca74b75e7c
            servicePort: 15672
          path: /
        - backend:
            serviceName: ingress-ffe9286f7f9febf523d4256dc7fe29d4
            servicePort: 15672
          path: /rabbitmq
    - host: 4bplus001
      http:
        paths:
        - backend:
            serviceName: ingress-c00548c68466a274af357bb0662168be
            servicePort: 15672
          path: /
        - backend:
            serviceName: ingress-35ba4a2f910ce8547409d3b981be2bff
            servicePort: 15672
          path: /rabbitmq
kind: List
